apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fashion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 731872836867.dkr.ecr.ap-south-1.amazonaws.com/fashion-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLIENT_URL
            - name: RAZORPAY_KEY_ID
              valueFrom:
               secretKeyRef:
                  name: payment-secret
                  key: RAZORPAY_KEY_ID
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
               secretKeyRef:
                 name: payment-secret
                 key: RAZORPAY_KEY_SECRET